### ISSUE TITLE
Volunteer missing from database

### ISSUE THREAD

**Issue by jopowers** [megandalster/rmhp-homebase#19]
We have a volunteer that was present and active in the database that is no longer available. When we search her we get the error message: "not in database". The volunteer's name is: Chingxia "Cee" Banks.

**Comment by megandalster** [comment]
I replaced the quotes in Chingxia "Cee" Banks by parentheses, so her name reads Chingxia (Cee) Banks and her info is there.  

In general, quotes (") don't work in a person's name -- it's good to stay away from them.  Other special characters are handled more gracefully.

I could work on a better fix if you would like... let me know.

Allen
