### ISSUE TITLE
Group Google Calendar in Homebase

### ISSUE THREAD

**Issue by jopowers** [megandalster/rmhp-homebase#22]
Hi Allen,

I hope you are well. The Group Google calendar is a "read only" document. I'm unable to make any changes etc. on it. I was going to create a new calendar but then I was afraid it would not link to Homebase. Please advise. Thanks! - Joanna

**Comment by megandalster** [comment]
Hi joanna,

To edit the calendar you need to log into your Google account using your email address first. Let me know if this works.

When I set up the calendar I gave editing privileges only to you.  Let me know if there are others.

Allen



Allen Tucker
allen@bowdoin.edu
207-841-1399



-------- Original message --------

**Comment by jopowers** [comment]
Hi Allen,,

That is how I sign in to the calendars –the Group calendar is the only one of all the calendars that still has a “read only” option. It won’t let me save and add things to it. I am able to edit, etc. in all the other calendars. Not sure why that one is different.

Joanna



Joanna A. Powers
Volunteer Coordinator
Ronald McDonald House of Providence, Inc.
45 Gay Street
Providence, RI 02905
Tel:(401)274-4447 X227
Fax:(401)751-3730
email: jpowers@rmhprovidence.org<mailto:jpowers@rmhprovidence.org>
web: www.rmhprovidence.org<http://www.rmhprovidence.org>

**Comment by megandalster** [comment]
Oops, looks like I set it up wrong. When I get back to a computer I'll fix that.  Sorry for the mixup! Allen



Allen Tucker
allen@bowdoin.edu
207-841-1399



-------- Original message --------

**Comment by jopowers** [comment]
Thanks Allen – no rush I appreciate it! Have a great weekend!

Joanna

Joanna A. Powers
Volunteer Coordinator
Ronald McDonald House of Providence, Inc.
45 Gay Street
Providence, RI 02905
Tel:(401)274-4447 X227
Fax:(401)751-3730
email: jpowers@rmhprovidence.org<mailto:jpowers@rmhprovidence.org>
web: www.rmhprovidence.org<http://www.rmhprovidence.org>
