### ISSUE TITLE
Changing military time and the hours worked

### ISSUE THREAD

**Issue by jopowers** [megandalster/rmhp-homebase#27]
Hi Allen,

Thanks for all your help with everything -it's looking good and moving right along!  Is there a way to change the military time when a volunteer enters their hours I can see 1300 instead of 1pm throwing some of our volunteers off. Also is there a way to total hours worked field (it totals at the end but the volunteer actually has to enter their shift hours, it would be easier if someone writes 9-1 that field would then populate 4. 

Thanks -Joanna

**Comment by megandalster** [comment]
Fixed so that 1300 shows as 1pm, but the other part is not easily fixed.

**Comment by jopowers** [comment]
Thanks Allen
