### ISSUE TITLE
Unable to log in volunteers by their user name

### ISSUE THREAD

**Issue by jopowers** [megandalster/rmhp-homebase#29]
We started to test user names yesterday and found we were unable to log in several volunteers. We tried a total of 4 volunteers and only one volunteer worked. The volunteer that worked was Paul Dow: user name: Paul4012532036. The following did not work: Jeanne Cohen, Suzanne Accetta, and Karen Angelone or: Jeanne6462866336, Suzanne4019464518, Karen4017287972.  We did completely log out and tried several times and it did not work.

**Comment by megandalster** [comment]
I reset Jeanne Cohen's password and then logged in successfully as Jeanne6462866336 with the default password.  Has Jeanne ever logged in and changed her password to something more secure?  

Same question for Suzanne and Karen.  Maybe Paul Dow's login worked because he never changed his password?  Just a guess about what's going on here.

Allen

**Comment by megandalster** [comment]
Joanna and Sue, why don't you reset the passwords of Suzanne and Karen so that they can log in, and then let's monitor this situation to see how many more of these pop up.  We can reopen and review this issue as needed.

**Comment by jopowers** [comment]
Hi Allen,

Thanks for all your help this weekend with all of the issues. Volunteer sign in still seems to be a concern. We have not shared Homebase with our volunteers yet, these issues I sent you are from me and Sue trying to "beta test" the system to get ready to train the volunteers.  No one changed any volunteer passwords, and are attempts were all first time.  What is interesting is now Jeanne Cohen is working fine. However I  still can't get in under Karen Angelone and I tried another volunteer that we have never entered before: Elaine Goudreau, or Elaine 4013161512 and it did not work either. Not sure what the next step should be, would we need to reset everyone's passwords?

**Comment by megandalster** [comment]
Okay, I'll take another look at this and will get back to you.  Resetting everyone's password would be mind-numbing... let's not go there!

**Comment by megandalster** [comment]
Okay, I have fixed this bug and reset all volunteers' passwords in the database to default.  Managers' passwords should not be affected.  Please beat on this issue to be sure that it is really fixed.  Allen

**Comment by jopowers** [comment]
Okay thanks Allen - we will work on this the next few days.
