### ISSUE TITLE
Deleting from the database

### ISSUE THREAD

**Issue by jopowers** [megandalster/rmhp-homebase#32]
I did a "test" volunteer named Betty Testing just to see what a it would look like signing in as a guest. I have deleted Betty Testing several times but she has not left the database.  Is there a way to purge records completely or will it always be there?

**Comment by megandalster** [comment]
Betty seems to be gone from your database now and I didn't do anything to cause that.  

I also failed to replicate this issue... when I try to remove a person, she is gone from the database.

**Comment by jopowers** [comment]
She is now gone - thanks
