### ISSUE TITLE
Volunteers access to the calendars

### ISSUE THREAD

**Issue by jopowers** [megandalster/rmhp-homebase#34]
Hi Allen,

Sue and I are continuing to test the database. We have noticed that a volunteer can currently remove/add
themselves or another person from the calendars. The only option we want our volunteers to have for calendars is to view them, or to add themselves to a shift that is vacant only. They should not be able to edit the calendar in any other way, or add another volunteer, etc.

**Comment by megandalster** [comment]
Okay, this one is fixed.  When a volunteer tries to edit a shift that has no vacancies, she is told "you cannot edit this shift."  When she tries to add a person to a vacancy, her name comes up as the only choice.  Hope that will be acceptable.  Try this out by logging in as Karen4017287972, but be sure to "publish" the calendar week before logging in.  Until you publish the week, the volunteer cannot even view it.  Allen
