### ISSUE TITLE
Excel export for Homebase

### ISSUE THREAD

**Issue by jopowers** [megandalster/rmhp-homebase#37]
Hi Allen,

We are having trouble again with getting the reports to drop into Excel. We were fine last week when the server was not on our website. We know how to move the export.csv to the URL and it was working fine. Now that it is attached to our website the URL at the top of the page when we run reports is: rmhprovidence.org/schedule/. It doesn't do anything when we change it to 'export.csv.' Please advise - many thanks!

**Comment by megandalster** [comment]
Joanna,

This looks like there may be a permissions issue at the root directory of Homebase — if so, Gabriel should be able to fix it.

Gabrielle, could you check that the path to the Homebase root is writable.  The software wants to write the file “export.csv” into the path rmhprovidence.org/schedule<http://rmhprovidence.org/schedule>, and the file isn’t getting there.  Let me know if you see any other possible cause for this problem.

Thanks,
Allen

On Oct 15, 2015, at 10:26 AM, jopowers <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Allen,

We are having trouble again with getting the reports to drop into Excel. We were fine last week when the server was not on our website. We know how to move the export.csv to the URL and it was working fine. Now that it is attached to our website the URL at the top of the page when we run reports is: rmhprovidence.org/schedule/<http://rmhprovidence.org/schedule/>. It doesn't do anything when we change it to 'export.csv.' Please advise - many thanks!

**Comment by megandalster** [comment]
Joanna, Gabriel,

Please ignore my last comment on this issue.

The fix to this is simple — just change the URL  rmhprovidence.org/schedule/<http://rmhprovidence.org/schedule/> to rmhprovidence.org/homebase/export.csv<http://rmhprovidence.org/homebase/export.csv> and your report should download as before.

Allen

On Oct 15, 2015, at 10:26 AM, jopowers <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Allen,

We are having trouble again with getting the reports to drop into Excel. We were fine last week when the server was not on our website. We know how to move the export.csv to the URL and it was working fine. Now that it is attached to our website the URL at the top of the page when we run reports is: rmhprovidence.org/schedule/<http://rmhprovidence.org/schedule/>. It doesn't do anything when we change it to 'export.csv.' Please advise - many thanks!

**Comment by jopowers** [comment]
Thanks that worked all set.

**Comment by megandalster** [comment]
Allen,

Please send this request to support@coursevector.com thanks!
