### ISSUE TITLE
Shift Vacancy Report

### ISSUE THREAD

**Issue by jopowers** [megandalster/rmhp-homebase#40]
Hi Allen,

We have noticed that the numbers on our Shift Vacancy Report are off they correlate with every time we make a change rather than actually listing the number of vacancies. For example if I change a shift several times it will count that as vacancies even if the shift has been filled. So the numbers for the Family Room are off on that report.  For example we only have 90 shifts in a month for the Family Room and yet the report lists hundreds. Thanks for your help!

Joanna

**Comment by megandalster** [comment]
Wow, these were really off!  I have fixed this now and renamed the report "Volunteers in Shifts/Vacancies". Each entry in the table reports the number of volunteers in a shift alongside the number of vacancies in that shift.  The fix will show up when it is installed on your server.
