### ISSUE TITLE
Volunteer Available for a Shift

### ISSUE THREAD

**Issue by jopowers** [megandalster/rmhp-homebase#41]
Hi Allen,

We have noticed that both Family Room and House Volunteers are showing up when we select a volunteer with availability. Rather than just House or just Family room, it's a running list of all volunteers.
Thanks for your help!

Joanna

**Comment by megandalster** [comment]
Fixed bug in both the calendar and the master schedule.  Fix will show up when software is updated at your web site.

**Comment by jopowers** [comment]
Thanks so much for your help Allen - hope you had a nice holiday - Happy New Year!
