### ISSUE TITLE
Concerns for RMH - Providence Homebase

### ISSUE THREAD

**Issue by jopowers** [megandalster/rmhp-homebase#42]
Hi Allen,

Thank you so much for offering to help out with Hombase.  We have a couple of items that we need assistance with. I will create separate issues rather than lumping them all together. If you have any questions at all please let me know - And thank you again!

Issue #1 - We have several volunteers that come to the House every other week. For example Elizabeth Marcantonio does every other Tuesday from 1pm-5pm. She is on the master schedule as an odd week.  So on week 51 of 2016 she is on for her shift, as she should be.  The next week is Week 1 for 2017 and it is also an odd week.  This would lead to a ton of confusion as it is two weeks in a row. We would need the week schedule to be changed to Week 1 as a even not odd week.

**Comment by megandalster** [comment]
This one is now fixed as soon as your web host installs the corrected code that I will send separately.

**Comment by megandalster** [comment]
PS Once the fix is made on your server, you will need to clear and regenerate any weeks in 2017 that you had generated.  Now the first week in January will show as week 00: even (not week 01: odd), so weeks should alternate properly between December and January for bi-weekly volunteers.
