### ISSUE TITLE
Issue with Volunteer on Report

### ISSUE THREAD

**Issue by jopowers** [megandalster/rmhp-homebase#44]
Hi Allen,

Thank you so much for all your help this weekend - I really appreciate it.  We discovered one more issue that I thought I would bring up before we upload to our Website.   We have a volunteer her name is Samantha Zambuto, all of her hours are logged, etc. but her name does not appear on the Report for hours, we have to manually add her to the report every month. Is there something strange about her record?  

Thanks!

Joanna

**Comment by megandalster** [comment]
Hi Joanna,

This was another bug in the code, which I have fixed and will send the fix on to Tina and Coursevector so that they can update your live version of Homebase.  

Before I do that, let me know if there are any other issues I need to look at, so that we get them all at once.

Thanks,
Allen
