### ISSUE TITLE
Problem Recording hours in Homebase

### ISSUE THREAD

**Issue by jopowers** [megandalster/rmhp-homebase#49]
Hi Allen,

I hope this message finds you well. I'm sorry to bother you....I was hoping you can give me some advice. We have a volunteer that we can no longer log her hours. We have checked with other volunteers and tried ourselves and we are only having difficulty with her hours. She is a Family Room Volunteer: Suzanne Accetta 4019464518. If you get a chance can you look at her record to see what might be the issue?

Thank you so much!  - Joanna

**Comment by megandalster** [comment]
fixed.
